version: '3.8'

services:
  apache-php:
    build: .
    container_name: laravel-osssd-${CLUSTER_NAME}
    ports:
      - "8080:80"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
